pull_request_rules:
  - name: Request review from team
    description: Request review from a specific team when checks are green.
    conditions:
      - -closed
      - "#approved-reviews-by = 0"
      - "#changes-requested-reviews-by = 0"
      - "review-requested != @Ebkarlibya/the-pr-patriots "
    actions:
      request_reviews:
        teams:
          - Ebkarlibya/the-pr-patriots
queue_rules: []
